name: VDP Presentation to Neo4j

on: workflow_dispatch

jobs:
  all-presentations:
    runs-on: ubuntu-latest
    name: Export VDP presentations to Neo4j instance
    outputs:
      json: ${{ steps.issue-credential.outputs.json }}
    steps:
      - name: Get Access Token
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.6
        id: tokenCreate
        with:
          operation-id: tokenCreate
          api-base-url: https://test.transmute.industries
          did: did:web:test.transmute.industries:organizations:org_OYSeCasVPVgBM59v
          token-endpoint: https://test.transmute.industries/oauth/token
          token-audience: https://test.transmute.industries
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
      - name: Gets Received Presentations
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.6
        id: getPresentationsSharedWithMe
        with:
          operation-id: getPresentationsSharedWithMe
      - name: set received to env
        run: echo "received_presentations=$(echo $verifiable_data_platform_api_response | jq -c '.items' | jq -c 'map(.verifiablePresentation)' | jq -c .[0:9])" >> $GITHUB_ENV
      - name: Merge Received Query from Document
        uses: transmute-industries/jsonld-to-cypher@v0.1.3
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          document: ${{ env.received_presentations }}
          operation: merge

      - name: Gets Sent Presentations
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.6
        id: getPresentationsSharedWithOthers
        with:
          operation-id: getPresentationsSharedWithOthers
      - name: set received to env
        run: echo "sent_presentations=$(echo $verifiable_data_platform_api_response | jq -c '.items' | jq -c 'map(.verifiablePresentation)' | jq -c .[0:9])" >> $GITHUB_ENV
      - name: Merge Sent Query from Document
        uses: transmute-industries/jsonld-to-cypher@v0.1.3
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          operation: merge
          document: ${{ env.sent_presentations }}
