name: VDP Presentation to Neo4j

on: workflow_dispatch

jobs:
  all-presentations:
    runs-on: ubuntu-latest
    name: Export VDP presentations to Neo4j instance
    outputs:
      json: ${{ steps.issue-credential.outputs.json }}
    steps:
      - name: Get Access Token
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.5
        id: tokenCreate
        with:
          operation-id: tokenCreate
          api-base-url: ${{ secrets.API_BASE_URL }}
          did: ${{ secrets.ORGANIZATION_DID_WEB }}
          token-endpoint: ${{ secrets.TOKEN_ENDPOINT }}
          token-audience: ${{ secrets.TOKEN_AUDIENCE }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
      - name: Gets Received Presentations
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.5
        id: getPresentationsSharedWithMe
        with:
          operation-id: getPresentationsSharedWithMe
      - name: Add received to file
        run: echo $verifiable_data_platform_api_response >> received-presentations.json
      - name: set received to presentation
        run: cat received-presentations.json | jq .items[0] > received-presentations.json
      - name: Env received
        id: getreceived
        run: echo "::set-output name=presentations::$(cat received-presentations.json)"
      - name: Merge Received Query from Document
        uses: transmute-industries/jsonld-to-cypher@v0.1.3
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          operation: merge
          document: ${{ steps.getreceived.outputs.presentations }}
      - name: Gets Sent Presentations
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.5
        id: getPresentationsSharedWithOthers
        with:
          operation-id: getPresentationsSharedWithOthers
      - name: Add sent to file
        run: echo $verifiable_data_platform_api_response >> sent-presentations.json
      - name: set sent to presentation
        run: cat sent-presentations.json | jq .items[0] > sent-presentations.json
      - name: Env sent
        id: getsent
        run: echo "::set-output name=presentations::$(cat sent-presentations.json)"
      - name: Merge Sent Query from Document
        uses: transmute-industries/jsonld-to-cypher@v0.1.3
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          operation: merge
          document: ${{ steps.getsent.outputs.presentations }}
