name: Issue Credential

on: workflow_dispatch

jobs:
  all-presentations:
    runs-on: ubuntu-latest
    name: Export VDP presentations to Neo4j instance
    outputs:
      json: ${{ steps.issue-credential.outputs.json }}
    steps:
      - name: Get Access Token
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.2
        id: getAccessToken
        with:
          operation-id: getAccessToken
          api-base-url: ${{ secrets.API_BASE_URL }}
          did: ${{ secrets.ORGANIZATION_DID_WEB }}
          token-endpoint: ${{ secrets.TOKEN_ENDPOINT }}
          token-audience: ${{ secrets.TOKEN_AUDIENCE }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
      - name: Gets Credentials
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.2
        id: getCredentials
        with:
          operation-id: getCredentials
      - name: debug
        run: node -v
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge Query from Document
        uses: ./

      # - name: Merge Query from Document
      #   uses: transmute-industries/jsonld-to-cypher@v0.1.2
      #   id: merge
      #   with:
      #     neo4j-uri: ${{ secrets.NEO4J_URI }}
      #     neo4j-user: ${{ secrets.NEO4J_USERNAME }}
      #     neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
      #     operation: merge
      #     document: |
      #       {
      #         "@context": [
      #           "https://www.w3.org/2018/credentials/v1",
      #           "https://w3id.org/vc-revocation-list-2020/v1"
      #         ],
      #         "id": "urn:uuid:4d432bf3-ca45-4070-999a-eb48c4f3f416",
      #         "type": ["VerifiableCredential"],
      #         "issuer": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      #         "issuanceDate": "2010-01-01T19:23:24Z",
      #         "credentialStatus": {
      #           "id": "https://api.did.actor/revocation-lists/1.json#0",
      #           "type": "RevocationList2020Status",
      #           "revocationListIndex": 0,
      #           "revocationListCredential": "https://api.did.actor/revocation-lists/1.json"
      #         },
      #         "credentialSubject": { "id": "did:example:123" },
      #         "proof": {
      #           "type": "Ed25519Signature2018",
      #           "created": "2022-10-30T20:15:27Z",
      #           "verificationMethod": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
      #           "proofPurpose": "assertionMethod",
      #           "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..eQrU_BmLRp0CtI_gTKTl5UqcbKNy7n7hCtt0dvsYVdx0hR2Mbm4g53apLJ4fApy-dNvrvaJPpIC0OY_xG_e_Bg"
      #         }
      #       }
      # Query for all the verifiable presentations on the users organization, both sent and received.
      # - name: Get Credentials
      #   uses: transmute-industries/verifiable-data-platform-github-action@v0.0.2
      #   id: getCredentials
      #   with:
      #     operation-id: getCredentials
      #     api-base-url: ${{ secrets.API_BASE_URL }}

      # Convert the VP from JSON-LD to cypher.
      # Commit the cypher to the Neo4j instance
